name: "Publish project"

on:
  workflow_call:
    inputs:
      solution:
        description: "Project solution"
        required: false
        type: string
      projectsToPack:
        description: "Projects to pack and push"
        required: false
        type: string
      nuget:
        description: "Publish nuget packages"
        required: true
        type: boolean
jobs:
  publish_nuget:
    name: Publish NuGet
    runs-on: ubuntu-latest
    if: ${{ inputs.nuget }}
    steps:
      - uses: ../actions/nuget/publish.yaml
        with:
          solution: ${{ inputs.solution }}
          projectsToPack: ${{ inputs.projectsToPack }}
